<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class listController extends Controller
{
    public function getList()
    {
        $arr = [
            [
                "code" => "200",
                "content" => [
                    "pageNum" => 1,
                    "count" => 110,
                    "pageSize" => 2000,
                    "totalPage" => 1,
                    "result" => [
                        [
                            "areaId" => "110101000000",
                            "countyName" => "东城区",
                            "provinceName" => "北京市",
                            "cityName" => "市辖区",
                            "poorType" => "notpoor",
                            "idx" => 12,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528519301000,
                            "updateAt" => 1530094318000,
                            "configMap" => [
                                "system=>population" => "30000000",
                                "system=>banner" => "https=>//upload.17shanyuan.com/country/b1dd34a2e61402a03221e1c9c7943d934aefbcfc.png",
                                "system=>platformFeeRate" => "100",
                                "system=>interest" => "北京故宫天安门毛主席告诉我们打倒一切反动派的纸老虎要翻身",
                                "system=>scenery" => "故宫北京故宫天安门毛主席告诉我们打倒一切反动派的纸老虎要翻身",
                                "system=>poorAmount" => "156000"
                            ]
                        ],
                        [
                            "areaId" => "320684000000",
                            "countyName" => "海门市",
                            "provinceName" => "江苏省",
                            "cityName" => "南通市",
                            "poorType" => "normal",
                            "idx" => 20,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1529043924000,
                            "updateAt" => 1529549136000,
                            "configMap" => [
                                "system=>population" => "50",
                                "system=>banner" => "https=>//upload.17shanyuan.com/country/8581468314314c09557619d1fc910543e2175dbc.png",
                                "system=>platformFeeRate" => "100",
                                "system=>interest" => "故宫",
                                "system=>scenery" => "唱歌",
                                "system=>poorAmount" => "12"
                            ]
                        ],
                        [
                            "areaId" => "621027000000",
                            "countyName" => "镇原县",
                            "provinceName" => "甘肃省",
                            "cityName" => "庆阳市",
                            "poorType" => "normal",
                            "idx" => 22,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528280582000,
                            "updateAt" => 1530776233000,
                            "configMap" => [
                                "system=>population" => "123",
                                "system=>banner" => "https=>//upload.17shanyuan.com/country/c887891b2634befd6746d37660c855a9be86b445.gif",
                                "system=>platformFeeRate" => "100",
                                "system=>interest" => "敦煌",
                                "system=>scenery" => "敦煌的城",
                                "system=>poorAmount" => "12"
                            ]
                        ],
                        [
                            "areaId" => "120110000000",
                            "countyName" => "东丽区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>platformFeeRate" => "100",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/675fa11f8d17e02e2b53b7dff9dc3ee94d8aeb1c.png"
                            ]
                        ],
                        [
                            "areaId" => "120111000000",
                            "countyName" => "西青区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>platformFeeRate" => "70",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/2bc318d055521b97d7d21ab41293766d64bbdca5.png"
                            ]
                        ],
                        [
                            "areaId" => "120112000000",
                            "countyName" => "津南区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>platformFeeRate" => "30",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/8609099f215f0cc17b6398ce3cd1650ebec1c3af.png"
                            ]
                        ],
                        [
                            "areaId" => "120113000000",
                            "countyName" => "北辰区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "2",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/add792197f00430de7033c499dd89d1606bb49df.png",
                                "system=>platformFeeRate" => "30",
                                "system=>interest" => "集结集结军军军军军军军军军军",
                                "system=>scenery" => "集结集结军军军军军军军军军军",
                                "system=>poorAmount" => "2"
                            ]
                        ],
                        [
                            "areaId" => "120114000000",
                            "countyName" => "武清区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "120115000000",
                            "countyName" => "宝坻区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "85.13万",
                                "system=>banner" => "https=>//upload.17shanyuan.com/country/faefadea8a64b8f93b5511458088b2b8b0b96029.png",
                                "system=>platformFeeRate" => "10",
                                "system=>interest" => "广济寺、帝景温泉度假村、玉佛宫博物馆、松江生态园、小辛码头村",
                                "system=>scenery" => "北温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "120116000000",
                            "countyName" => "滨海新区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "120221000000",
                            "countyName" => "宁河区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "120223000000",
                            "countyName" => "静海区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "120225000000",
                            "countyName" => "蓟州区",
                            "provinceName" => "天津市",
                            "cityName" => "市辖区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "130203000000",
                            "countyName" => "路北区",
                            "provinceName" => "河北省",
                            "cityName" => "唐山市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528969231000,
                            "updateAt" => 1528969231000,
                            "configMap" => [
                                "system=>platformFeeRate" => "300",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/026dc0c86e32e7abc2924dc3ca7daf4bca2f7000.png"
                            ]
                        ],
                        [
                            "areaId" => "130223000000",
                            "countyName" => "滦县",
                            "provinceName" => "河北省",
                            "cityName" => "唐山市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1529498154000,
                            "updateAt" => 1529498154000,
                            "configMap" => [
                                "system=>platformFeeRate" => "0",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/4faa35374a1022b23ffabd0de18fd61b387461a8.gif"
                            ]
                        ],
                        [
                            "areaId" => "130725000000",
                            "countyName" => "尚义县",
                            "provinceName" => "河北省",
                            "cityName" => "张家口市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528280582000,
                            "updateAt" => 1531816180000,
                            "configMap" => [
                                "system=>platformFeeRate" => "80",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/04ee501237d93820ac09bbc0cedfe1f3ab746084.jpeg"
                            ]
                        ],
                        [
                            "areaId" => "130729000000",
                            "countyName" => "万全县",
                            "provinceName" => "河北省",
                            "cityName" => "张家口市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "130733000000",
                            "countyName" => "崇礼区",
                            "provinceName" => "河北省",
                            "cityName" => "张家口市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "12.6万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_846957849cdafa46f4e987f4906be26b.jpeg",
                                "system=>interest" => "石嘴子遗址、大沟门遗址、下石亩遗址",
                                "system=>poorAmount" => "16682",
                                "system=>scenery" => "东亚大陆性季风气候中温带亚干旱区"
                            ]
                        ],
                        [
                            "areaId" => "140123000000",
                            "countyName" => "娄烦县",
                            "provinceName" => "山西省",
                            "cityName" => "太原市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "140203000000",
                            "countyName" => "矿区",
                            "provinceName" => "山西省",
                            "cityName" => "大同市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1529497767000,
                            "updateAt" => 1529497767000,
                            "configMap" => [
                                "system=>population" => "12",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/02baf76e7025d0a2133a5fee60ec4733f62fd5dc.jpeg",
                                "system=>platformFeeRate" => "0",
                                "system=>poorAmount" => "1"
                            ]
                        ],
                        [
                            "areaId" => "140222000000",
                            "countyName" => "天镇县",
                            "provinceName" => "山西省",
                            "cityName" => "大同市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "21.38万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_47298858dc000756300bf8ecb8087307.jpeg",
                                "system=>interest" => "慈云寺，盘山，新平古城",
                                "system=>poorAmount" => "27159",
                                "system=>scenery" => "温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "140223000000",
                            "countyName" => "广灵县",
                            "provinceName" => "山西省",
                            "cityName" => "大同市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "18.8万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_64142f1dc52ea27843624bcc1454e818.jpeg",
                                "system=>interest" => "水神堂、白羊峪、汉白玉石林、千福山、圣佛寺松涛",
                                "system=>scenery" => "中温带大陆性半干旱季风气候",
                                "system=>poorAmount" => "30387"
                            ]
                        ],
                        [
                            "areaId" => "140524000000",
                            "countyName" => "陵川县",
                            "provinceName" => "山西省",
                            "cityName" => "晋城市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "140623000000",
                            "countyName" => "右玉县",
                            "provinceName" => "山西省",
                            "cityName" => "朔州市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529407725000,
                            "configMap" => [
                                "system=>population" => "11.4万",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/2b2ae49c5fb60a4f823cfbd22d1a4108baaf52fa.png",
                                "system=>platformFeeRate" => "1000",
                                "system=>interest" => "古长城、杀虎口、宝宁寺",
                                "system=>scenery" => "温带大陆性季风气候",
                                "system=>poorAmount" => "18166"
                            ]
                        ],
                        [
                            "areaId" => "140724000000",
                            "countyName" => "昔阳县",
                            "provinceName" => "山西省",
                            "cityName" => "晋中市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "140925000000",
                            "countyName" => "宁武县",
                            "provinceName" => "山西省",
                            "cityName" => "忻州市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "15万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_f199a37af339aacf9ed767e5086f9b33.jpeg",
                                "system=>interest" => "芦芽山、荷叶坪风景区、管涔山国家森林公园、万年冰洞",
                                "system=>poorAmount" => "25077",
                                "system=>scenery" => "温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "140926000000",
                            "countyName" => "静乐县",
                            "provinceName" => "山西省",
                            "cityName" => "忻州市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "16万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_995b475302a5a9f5b826624cb642a2d3.jpeg",
                                "system=>interest" => "玉石驼峰、天柱龙泉、神烟风洞",
                                "system=>poorAmount" => "24271",
                                "system=>scenery" => "北方季风气候"
                            ]
                        ],
                        [
                            "areaId" => "140927000000",
                            "countyName" => "神池县",
                            "provinceName" => "山西省",
                            "cityName" => "忻州市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "140932000000",
                            "countyName" => "偏关县",
                            "provinceName" => "山西省",
                            "cityName" => "忻州市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "11万人",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_f7da39492ea47ad39b88edeecdf0db7d.jpeg",
                                "system=>interest" => "明长城、老牛湾、长城古堡、偏关八景",
                                "system=>poorAmount" => "13296",
                                "system=>scenery" => "温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "141028000000",
                            "countyName" => "吉县",
                            "provinceName" => "山西省",
                            "cityName" => "临汾市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "141030000000",
                            "countyName" => "大宁县",
                            "provinceName" => "山西省",
                            "cityName" => "临汾市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "6.8万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_bfbd5e472833948f30f5fe5620094614.jpeg",
                                "system=>interest" => "黄河仙子祠、将军墓、双锁山、十八罗汉洞、二郎山",
                                "system=>scenery" => "温带大陆性季风气候",
                                "system=>poorAmount" => "15488"
                            ]
                        ],
                        [
                            "areaId" => "141032000000",
                            "countyName" => "永和县",
                            "provinceName" => "山西省",
                            "cityName" => "临汾市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "53539人",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_9471163fc3dc9a9356a53ae800f7c27d.jpeg",
                                "system=>interest" => "红军东征永和纪念馆、黄河乾坤湾",
                                "system=>scenery" => "暖温带大陆性季风气候",
                                "system=>poorAmount" => "11842"
                            ]
                        ],
                        [
                            "areaId" => "141123000000",
                            "countyName" => "兴县",
                            "provinceName" => "山西省",
                            "cityName" => "吕梁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "30万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_22533b648cce7e4d5f97f595ceb2286c.jpeg",
                                "system=>interest" => "晋绥边区革命纪念馆、“四八”烈士纪念馆、晋绥解放区烈士陵园",
                                "system=>poorAmount" => "50265",
                                "system=>scenery" => "温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "141124000000",
                            "countyName" => "临县",
                            "provinceName" => "山西省",
                            "cityName" => "吕梁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "65万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_367596cbf55d164eeec9bcc5f2d03f40.jpeg",
                                "system=>interest" => "碛口古镇、义居寺",
                                "system=>poorAmount" => "122629",
                                "system=>scenery" => "温带大陆性气候"
                            ]
                        ],
                        [
                            "areaId" => "141126000000",
                            "countyName" => "石楼县",
                            "provinceName" => "山西省",
                            "cityName" => "吕梁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "11.3万人",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_1f4b8f306cdb1edd2b15546f49e718d7.jpeg",
                                "system=>interest" => "兴东垣东岳庙、殿山圣母庙与元代戏台、四照楼、黄河弯",
                                "system=>poorAmount" => "31192",
                                "system=>scenery" => "温带大陆性季风气候"
                            ]
                        ],
                        [
                            "areaId" => "141127000000",
                            "countyName" => "岚县",
                            "provinceName" => "山西省",
                            "cityName" => "吕梁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "150124000000",
                            "countyName" => "清水河县",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "呼和浩特市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "150222000000",
                            "countyName" => "固阳县",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "包头市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "150429000000",
                            "countyName" => "宁城县",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "赤峰市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529407758000,
                            "configMap" => [
                                "system=>population" => "612140人",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/82224224d12f23e2db332a8dc4288923f561d143.png",
                                "system=>platformFeeRate" => "1000",
                                "system=>interest" => "辽中京遗址、右北平黑城遗址、黑里河自然保护区、法轮寺",
                                "system=>scenery" => "温带大陆性季风气候",
                                "system=>poorAmount" => "35131"
                            ]
                        ],
                        [
                            "areaId" => "150627000000",
                            "countyName" => "伊金霍洛旗",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "鄂尔多斯市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "150924000000",
                            "countyName" => "兴和县",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "乌兰察布市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "31.48万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_87dcf8d770676116ac4ac2e8b21e1772.jpeg",
                                "system=>interest" => "苏木山森林公园",
                                "system=>scenery" => "中温带大陆性季风气候",
                                "system=>poorAmount" => "16493"
                            ]
                        ],
                        [
                            "areaId" => "150926000000",
                            "countyName" => "察哈尔右翼前旗",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "乌兰察布市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "152527000000",
                            "countyName" => "太仆寺旗",
                            "provinceName" => "内蒙古自治区",
                            "cityName" => "锡林郭勒盟",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "210505000000",
                            "countyName" => "南芬区",
                            "provinceName" => "辽宁省",
                            "cityName" => "本溪市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1529550877000,
                            "updateAt" => 1529551010000,
                            "configMap" => [
                                "system=>platformFeeRate" => "13",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/2d66cc63b3f0825354b9800f50464fe5e8c3b3f5.gif"
                            ]
                        ],
                        [
                            "areaId" => "210522000000",
                            "countyName" => "桓仁满族自治县",
                            "provinceName" => "辽宁省",
                            "cityName" => "本溪市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "30万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_5771f488b8c2dff37a8ef517f23ecc7f.jpeg",
                                "system=>interest" => "望天洞、五女山、大雅河漂流、桓龙湖、冰臼奇观",
                                "system=>scenery" => "温带大陆性湿润气候",
                                "system=>poorAmount" => "16961"
                            ]
                        ],
                        [
                            "areaId" => "210624000000",
                            "countyName" => "宽甸满族自治县",
                            "provinceName" => "辽宁省",
                            "cityName" => "丹东市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/"
                            ]
                        ],
                        [
                            "areaId" => "222424000000",
                            "countyName" => "汪清县",
                            "provinceName" => "吉林省",
                            "cityName" => "延边朝鲜族自治州",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230129000000",
                            "countyName" => "延寿县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "哈尔滨市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230221000000",
                            "countyName" => "龙江县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "齐齐哈尔市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230225000000",
                            "countyName" => "甘南县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "齐齐哈尔市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230227000000",
                            "countyName" => "富裕县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "齐齐哈尔市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230382000000",
                            "countyName" => "密山市",
                            "provinceName" => "黑龙江省",
                            "cityName" => "鸡西市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230422000000",
                            "countyName" => "绥滨县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "鹤岗市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230524000000",
                            "countyName" => "饶河县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "双鸭山市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230624000000",
                            "countyName" => "杜尔伯特蒙古族自治县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "大庆市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230781000000",
                            "countyName" => "铁力市",
                            "provinceName" => "黑龙江省",
                            "cityName" => "伊春市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230811000000",
                            "countyName" => "郊区",
                            "provinceName" => "黑龙江省",
                            "cityName" => "佳木斯市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528879626000,
                            "updateAt" => 1528879626000,
                            "configMap" => [
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/372fd498d289a6df81c3e06002dd73abbb85459b.png"
                            ]
                        ],
                        [
                            "areaId" => "230826000000",
                            "countyName" => "桦川县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "佳木斯市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230881000000",
                            "countyName" => "同江市",
                            "provinceName" => "黑龙江省",
                            "cityName" => "佳木斯市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "230921000000",
                            "countyName" => "勃利县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "七台河市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "231025000000",
                            "countyName" => "林口县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "牡丹江市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "231102000000",
                            "countyName" => "爱辉区",
                            "provinceName" => "黑龙江省",
                            "cityName" => "黑河市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "231221000000",
                            "countyName" => "望奎县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "绥化市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "231222000000",
                            "countyName" => "兰西县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "绥化市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "231283000000",
                            "countyName" => "海伦市",
                            "provinceName" => "黑龙江省",
                            "cityName" => "绥化市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "232723000000",
                            "countyName" => "漠河县",
                            "provinceName" => "黑龙江省",
                            "cityName" => "大兴安岭地区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "310117000000",
                            "countyName" => "松江区",
                            "provinceName" => "上海市",
                            "cityName" => "市辖区",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528546773000,
                            "updateAt" => 1528546773000,
                            "configMap" => [
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/17a72ad260032977e4e683b4fd17e879869e669b.jpeg"
                            ]
                        ],
                        [
                            "areaId" => "320482000000",
                            "countyName" => "金坛市",
                            "provinceName" => "江苏省",
                            "cityName" => "常州市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1529498255000,
                            "updateAt" => 1529498255000,
                            "configMap" => [
                                "system=>platformFeeRate" => "200",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/e3830f03a0621468539c1c0c1cb7f1806cdfa605.jpeg"
                            ]
                        ],
                        [
                            "areaId" => "320582000000",
                            "countyName" => "张家港市",
                            "provinceName" => "江苏省",
                            "cityName" => "苏州市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1530093850000,
                            "updateAt" => 1530093850000,
                            "configMap" => [
                                "system=>platformFeeRate" => "10",
                                "system=>banner" => "https=>//upload.17shanyuan.com/country/df62ff9b8ba465cf6dc77e082b61a5616b6d311c.gif"
                            ]
                        ],
                        [
                            "areaId" => "321322000000",
                            "countyName" => "沭阳县",
                            "provinceName" => "江苏省",
                            "cityName" => "宿迁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "321324000000",
                            "countyName" => "泗洪县",
                            "provinceName" => "江苏省",
                            "cityName" => "宿迁市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "340621000000",
                            "countyName" => "濉溪县",
                            "provinceName" => "安徽省",
                            "cityName" => "淮北市",
                            "poorType" => "notpoor",
                            "idx" => 999999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528945088000,
                            "updateAt" => 1528945088000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "350723000000",
                            "countyName" => "光泽县",
                            "provinceName" => "福建省",
                            "cityName" => "南平市",
                            "poorType" => "notpoor",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528945264000,
                            "updateAt" => 1528945264000,
                            "configMap" => [
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/93596826d253e4a9e70c9c525f4ca825531af102.png"
                            ]
                        ],
                        [
                            "areaId" => "370285000000",
                            "countyName" => "莱西市",
                            "provinceName" => "山东省",
                            "cityName" => "青岛市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "75万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_5a6e19c580822faa04c11945d824c7ee.jpeg",
                                "system=>interest" => "龙海公园、月湖公园、南岚遗址、莱西湖、姜山湿地保护区",
                                "system=>poorAmount" => "9425",
                                "system=>scenery" => "温带海洋性季风气候"
                            ]
                        ],
                        [
                            "areaId" => "370724000000",
                            "countyName" => "临朐县",
                            "provinceName" => "山东省",
                            "cityName" => "潍坊市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "370786000000",
                            "countyName" => "昌邑市",
                            "provinceName" => "山东省",
                            "cityName" => "潍坊市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528445888000,
                            "updateAt" => 1528445888000,
                            "configMap" => [
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/e205b6f1db9814d2687546143e14eda4b986e567.gif"
                            ]
                        ],
                        [
                            "areaId" => "371202000000",
                            "countyName" => "莱城区",
                            "provinceName" => "山东省",
                            "cityName" => "莱芜市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "371203000000",
                            "countyName" => "钢城区",
                            "provinceName" => "山东省",
                            "cityName" => "莱芜市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "371327000000",
                            "countyName" => "莒南县",
                            "provinceName" => "山东省",
                            "cityName" => "临沂市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "371725000000",
                            "countyName" => "郓城县",
                            "provinceName" => "山东省",
                            "cityName" => "菏泽市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "410821000000",
                            "countyName" => "修武县",
                            "provinceName" => "河南省",
                            "cityName" => "焦作市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528957258000,
                            "updateAt" => 1528957274000,
                            "configMap" => [
                                "system=>platformFeeRate" => "123",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/5e0bec102005839eb9206e58f863a0fdcdc8ca16.png"
                            ]
                        ],
                        [
                            "areaId" => "411522000000",
                            "countyName" => "光山县",
                            "provinceName" => "河南省",
                            "cityName" => "信阳市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "451027000000",
                            "countyName" => "凌云县",
                            "provinceName" => "广西壮族自治区",
                            "cityName" => "百色市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "511528000000",
                            "countyName" => "兴文县",
                            "provinceName" => "四川省",
                            "cityName" => "宜宾市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "48.81万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_6a560bf34ca495d7b32e6a46f0a2da68.jpeg",
                                "system=>interest" => "石海洞乡、僰王山风景区",
                                "system=>scenery" => "亚热带湿润型气候",
                                "system=>poorAmount" => "53657"
                            ]
                        ],
                        [
                            "areaId" => "522631000000",
                            "countyName" => "黎平县",
                            "provinceName" => "贵州省",
                            "cityName" => "黔东南苗族侗族自治州",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "530827000000",
                            "countyName" => "孟连傣族拉祜族佤族自治县",
                            "provinceName" => "云南省",
                            "cityName" => "普洱市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "530829000000",
                            "countyName" => "西盟佤族自治县",
                            "provinceName" => "云南省",
                            "cityName" => "普洱市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "530902000000",
                            "countyName" => "临翔区",
                            "provinceName" => "云南省",
                            "cityName" => "临沧市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => [
                                "system=>population" => "32万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_6458cb0398254950986c68d622c4104e.jpeg",
                                "system=>interest" => "茶文化风情园、五老山森林公园、西门公园、灵山胜境",
                                "system=>poorAmount" => "41351",
                                "system=>scenery" => "亚热带山地季风气候"
                            ]
                        ],
                        [
                            "areaId" => "532301000000",
                            "countyName" => "楚雄市",
                            "provinceName" => "云南省",
                            "cityName" => "楚雄彝族自治州",
                            "poorType" => "notpoor",
                            "idx" => 999999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528944896000,
                            "updateAt" => 1528944896000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "532326000000",
                            "countyName" => "大姚县",
                            "provinceName" => "云南省",
                            "cityName" => "楚雄彝族自治州",
                            "poorType" => "notpoor",
                            "idx" => 999999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528944902000,
                            "updateAt" => 1528944902000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "533421000000",
                            "countyName" => "香格里拉县",
                            "provinceName" => "云南省",
                            "cityName" => "迪庆藏族自治州",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "533422000000",
                            "countyName" => "德钦县",
                            "provinceName" => "云南省",
                            "cityName" => "迪庆藏族自治州",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "533423000000",
                            "countyName" => "维西傈僳族自治县",
                            "provinceName" => "云南省",
                            "cityName" => "迪庆藏族自治州",
                            "poorType" => "notpoor",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1529551908000,
                            "updateAt" => 1529551908000,
                            "configMap" => [
                                "system=>platformFeeRate" => "13",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/d160f8524892da259eb80d4c115bd602deee70cb.gif"
                            ]
                        ],
                        [
                            "areaId" => "542125000000",
                            "countyName" => "丁青县",
                            "provinceName" => "西藏自治区",
                            "cityName" => "昌都地区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1529498526000,
                            "updateAt" => 1529498526000,
                            "configMap" => [
                                "system=>platformFeeRate" => "160",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/bd332024903d20dd26e21cb08a3a7e0d9096d6b0.png"
                            ]
                        ],
                        [
                            "areaId" => "610426000000",
                            "countyName" => "永寿县",
                            "provinceName" => "陕西省",
                            "cityName" => "咸阳市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529407236000,
                            "configMap" => [
                                "system=>population" => "20.7367万",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/335d6de8345571cf8bd095f51b1f0f3b540e2fb0.png",
                                "system=>platformFeeRate" => "700",
                                "system=>interest" => "翠屏山森林公园、武陵寺塔",
                                "system=>scenery" => "暖温带大陆季风性气候",
                                "system=>poorAmount" => "32689人"
                            ]
                        ],
                        [
                            "areaId" => "610428000000",
                            "countyName" => "长武县",
                            "provinceName" => "陕西省",
                            "cityName" => "咸阳市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529407649000,
                            "configMap" => [
                                "system=>population" => "18万",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/a79e6e024246f6fb0864d7c2814e393b5bbc3801.png",
                                "system=>platformFeeRate" => "700",
                                "system=>interest" => "昭仁寺、柳毅庙、城北公园",
                                "system=>scenery" => "暖温带大陆性季风气候",
                                "system=>poorAmount" => "25463人"
                            ]
                        ],
                        [
                            "areaId" => "610429000000",
                            "countyName" => "旬邑县",
                            "provinceName" => "陕西省",
                            "cityName" => "咸阳市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529917514000,
                            "configMap" => [
                                "system=>population" => "26.66万人",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/dfd284c9340bfd8791978d6e89cd5a353508bc83.png",
                                "system=>platformFeeRate" => "70",
                                "system=>interest" => "马栏革命旧址、石门山森林公园、唐家民居等",
                                "system=>scenery" => "温带大陆性季风气候",
                                "system=>poorAmount" => "37908人"
                            ]
                        ],
                        [
                            "areaId" => "610430000000",
                            "countyName" => "淳化县",
                            "provinceName" => "陕西省",
                            "cityName" => "咸阳市",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1529407682000,
                            "configMap" => [
                                "system=>population" => "19.682万人",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/02e6a9fc142e950e792eb7bf5ea26bb9a2d9f8c8.png",
                                "system=>platformFeeRate" => "700",
                                "system=>interest" => "爷台山 、关中大峡谷",
                                "system=>scenery" => "暖温带大陆性季风气候",
                                "system=>poorAmount" => "28567人"
                            ]
                        ],
                        [
                            "areaId" => "611002000000",
                            "countyName" => "商州区",
                            "provinceName" => "陕西省",
                            "cityName" => "商洛市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "57万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/support_area/oss_3e93620a837b036516a000f985e6e6a3.jpeg",
                                "system=>interest" => "文庙、商州城垣、二郎庙、商州城隍庙、龙山双塔、蒲峪生态园",
                                "system=>poorAmount" => "72983",
                                "system=>scenery" => "暖温带半湿润季风山地气候"
                            ]
                        ],
                        [
                            "areaId" => "611024000000",
                            "countyName" => "山阳县",
                            "provinceName" => "陕西省",
                            "cityName" => "商洛市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => [
                                "system=>population" => "47.40万",
                                "system=>banner" => "https=>//cdn.17shanyuan.com/country/8af53d88bdff6c4172ab9b4505e000111815b5af.jpeg",
                                "system=>platformFeeRate" => "30",
                                "system=>interest" => "天竺山、月亮洞、白龙洞、太白洞、石人",
                                "system=>scenery" => "亚热带季风性半湿润山地气候",
                                "system=>poorAmount" => "108611"
                            ]
                        ],
                        [
                            "areaId" => "620522000000",
                            "countyName" => "秦安县",
                            "provinceName" => "甘肃省",
                            "cityName" => "天水市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "621022000000",
                            "countyName" => "环县",
                            "provinceName" => "甘肃省",
                            "cityName" => "庆阳市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "621023000000",
                            "countyName" => "华池县",
                            "provinceName" => "甘肃省",
                            "cityName" => "庆阳市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "621026000000",
                            "countyName" => "宁县",
                            "provinceName" => "甘肃省",
                            "cityName" => "庆阳市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "632623000000",
                            "countyName" => "甘德县",
                            "provinceName" => "青海省",
                            "cityName" => "果洛藏族自治州",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "632726000000",
                            "countyName" => "曲麻莱县",
                            "provinceName" => "青海省",
                            "cityName" => "玉树藏族自治州",
                            "poorType" => "country",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1529407780000,
                            "configMap" => [
                                "system=>platformFeeRate" => "1000",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/056963332f964757ac855b515612885c67edb8a7.png"
                            ]
                        ],
                        [
                            "areaId" => "640323000000",
                            "countyName" => "盐池县",
                            "provinceName" => "宁夏回族自治区",
                            "cityName" => "吴忠市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280581000,
                            "updateAt" => 1528280581000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "640422000000",
                            "countyName" => "西吉县",
                            "provinceName" => "宁夏回族自治区",
                            "cityName" => "固原市",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "0",
                            "otherinfo2" => "0",
                            "isDelete" => 0,
                            "createAt" => 1528280582000,
                            "updateAt" => 1528280582000,
                            "configMap" => []
                        ],
                        [
                            "areaId" => "640521000000",
                            "countyName" => "中宁县",
                            "provinceName" => "宁夏回族自治区",
                            "cityName" => "中卫市",
                            "poorType" => "notpoor",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528955965000,
                            "updateAt" => 1528955965000,
                            "configMap" => [
                                "system=>platformFeeRate" => "125",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/60a16e5b03a31741d92a519b13023f868e7a7d2b.png"
                            ]
                        ],
                        [
                            "areaId" => "653101000000",
                            "countyName" => "喀什市",
                            "provinceName" => "新疆维吾尔自治区",
                            "cityName" => "喀什地区",
                            "poorType" => "normal",
                            "idx" => 99999,
                            "otherinfo1" => "1",
                            "otherinfo2" => "1",
                            "isDelete" => 1,
                            "createAt" => 1528956058000,
                            "updateAt" => 1528957036000,
                            "configMap" => [
                                "system=>platformFeeRate" => "900",
                                "system=>banner" => "https=>//cdnt.17shanyuan.com/country/6cce0456148bd99e10b3999d155579dfe790e1bf.png"
                            ]
                        ]
                    ]
                ],
                "message" => "Request Success",
                "timestamp" => "1532339141448"
            ]
        ];
        return json_encode($arr);
    }
}
